name: delivery_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.5
  intl: ^0.19.0
  
  # ✅ Firebase Dependencies
  firebase_core: ^2.27.2
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.4
  firebase_messaging: ^14.9.3
  firebase_analytics: ^10.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/lang/en-US.json
    - assets/lang/ml-IN.json

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  android: true
  ios: true
  web: true
  fullscreen: true
