// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYgRymzB3KBPgTdatUvky_5V7wr-ua9rY',
    appId: '1:157055624033:web:a5afac0bce14c58faedb20',
    messagingSenderId: '157055624033',
    projectId: 'esupplycodelivary',
    authDomain: 'esupplycodelivary.firebaseapp.com',
    storageBucket: 'esupplycodelivary.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2d19yupQ_sQHLIfkJ8mawcO-3hQt5Xw4',
    appId: '1:157055624033:android:cc10ae4debfbc2aaaedb20',
    messagingSenderId: '157055624033',
    projectId: 'esupplycodelivary',
    storageBucket: 'esupplycodelivary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl0iOD53T7DmUcYptWSnC9XUGu5pijnPI',
    appId: '1:157055624033:ios:bf37f81b375d4867aedb20',
    messagingSenderId: '157055624033',
    projectId: 'esupplycodelivary',
    storageBucket: 'esupplycodelivary.firebasestorage.app',
    iosBundleId: 'com.example.delivery1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl0iOD53T7DmUcYptWSnC9XUGu5pijnPI',
    appId: '1:157055624033:ios:bf37f81b375d4867aedb20',
    messagingSenderId: '157055624033',
    projectId: 'esupplycodelivary',
    storageBucket: 'esupplycodelivary.firebasestorage.app',
    iosBundleId: 'com.example.delivery1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYgRymzB3KBPgTdatUvky_5V7wr-ua9rY',
    appId: '1:157055624033:web:e0928a696c91094faedb20',
    messagingSenderId: '157055624033',
    projectId: 'esupplycodelivary',
    authDomain: 'esupplycodelivary.firebaseapp.com',
    storageBucket: 'esupplycodelivary.firebasestorage.app',
  );
}
